### ISSUE TITLE
Unable to install emulator in webOS studio

### ISSUE THREAD

**Issue by AkashRewal** [webos-tools/webos-studio#2]
Type: <b>Bug</b>

Sample Test webOS Studio
Unable to install emulator in webOS studio

Extension version: 2.1.0-beta.1
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by YoungeunKim** [comment]
This bug report was created by webOS Studio internal testing.
I'll close this issue.

**Comment by YoungeunKim** [comment]
This bug report was created by webOS Studio internal testing.
I'll close this issue.
