### ISSUE TITLE
add extension to open vsx registry

### ISSUE THREAD

**Issue by RodrigoDornelles** [webos-tools/webos-studio#3]
for [vscodium](https://vscodium.com) users or your own vscode build.

 * <https://open-vsx.org>

**Comment by RodrigoDornelles** [comment]
@YoungeunKim Why this issue is closed?

**Comment by YoungeunKim** [comment]
Sorry, I missed the comment. 
We plan to release only VS code marketplace. 

Thanks for the suggestion.
