### ISSUE TITLE
Unable to run web inspector on Mac 

### ISSUE THREAD

**Issue by JamieNandhraPezone** [webos-tools/webos-studio#4]
I am trying to setup the debugger on my Mac and keep receiving the same error message `Error! Failed to run a web inspector.`

I have tried setting `webos.chromeExecutable` in the `settings.json` to:

`"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"`
`"/Applications/Google Chrome.app"`

I'm using 

VS Code: `Version: 1.92.0`
Mac OS: `14.5`
Extension: `2.1.0`

**Comment by YoungeunKim** [comment]
The bug is not reproducible on 2 Mac PCs with the paths in settings.json

```
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
"/Applications/Google Chrome.app"
```

<The information> 
host PC#1

- macOS Big Sur : 11.7.10
- CLI : v3.1.1
- webOS Studio : v2.1.0
- Chrome : 126.0.0.0

host PC#2
- macOS Sonoma (M1) : 14.4.1
- CLI : v3.1.1
- webOS Studio : v2.1.0
- VS Code : 1.19.1
- Chrome : 127.0.6533.100


I'd like to know the error details. 
Could you try to debug the app using ares-cli command on your Mac? 

1. Install app to your device by ares-install command
`"ares-install --device target com.example.sampleapp_1.0.0_all.ipk"`
refer to : https://www.webosose.org/docs/tools/sdk/cli/cli-user-guide/#ares-install

2. Debug the installed app by ares-insepect command. 
`"ares-inspect --device target --app com.example.sampleapp`
refer to : https://www.webosose.org/docs/tools/sdk/cli/cli-user-guide/#ares-inspect

Please execute "ares-inspect --app [APPID] -v" ("-v" option is to display log of CLI) and share the logs.

**Comment by JamieNandhraPezone** [comment]
These are the results i get from the install and inspect commands

Install

```
(node:4256) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Info] Set target device : TV
Installing package io.we3world.artlume_0.0.1_all.ipk
.   Processing
(node:4256) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Success
```

Inspect

```
(node:4265) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Info] Set target device : TV
Application Debugging - http://localhost:65316/devtools/inspector.html?ws=localhost:65316/devtools/page/6547E99F6728DB49A285CE6DA1BE9A06
```

**Comment by YoungeunKim** [comment]
Thank you. 

1. What is your target(TV) type? TV Simulator, TV emulator or TV device? 
2. What is your app type? web app or enact app? 
3. Please use "/Applications/Google Chrome.app" path. There are two VS Code's setting.json. "User" and "Workspace" in setting(Code -> Settings... -> Settings")  Please check the chrome path in two settings.json files. 
5. Please copy and paste the "http://localhost:65316/ ~~ " in CLI Log to chrome browser. Is it working? 
6. Please share OUTPUT logs when "Failed to run a web inspector." is shown. 
You should select "webOS Studio" option in VS code's  OUTPUT terminal to see the webOS Studio's log.
refer to :https://www.webosose.org/docs/tools/sdk/vs-code-extension/#process-log

**Comment by JamieNandhraPezone** [comment]
1. Its a C1 device
2. I've tried a web and an enact app.
3. i've updated the Workspaces settings too
4. The URL in the CLI log works fine in the browser.
5.  This is what i see in the output log

```
[Executing] ares-setup-device -F
------------------------------------------------
[
    {
        "profile": "tv",
        "name": "TV",
        "default": true,
        "deviceinfo": {
            "ip": "192.168.1.135",
            "port": "9922",
            "user": "prisoner"
        },
        "connection": [
            "ssh"
        ],
        "details": {
            "platform": "starfish",
            "privatekey": "TV_webos",
            "passphrase": "0C45D2",
            "description": "new device description"
        }
    },
    {
        "profile": "tv",
        "name": "emulator",
        "default": false,
        "deviceinfo": {
            "ip": "127.0.0.1",
            "port": "6622",
            "user": "developer"
        },
        "connection": [
            "ssh"
        ],
        "details": {
            "platform": "starfish",
            "privatekey": "webos_emul",
            "description": "LG webOS TV Emulator"
        }
    }
]

[Error] (node:7203) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

[Executing] ares-inspect  com.mycompany.hellorenative -d TV
------------------------------------------------
[Info] Set target device : TV

Application Debugging - http://localhost:52682/devtools/inspector.html?ws=localhost:52682/devtools/page/5497DDFEEC6001D1BF37F937246BFB35
```

**Comment by YoungeunKim** [comment]
Thanks for checking.

The debugging operation is working fine. 
However, webOS Studio handled ares-CLI's node warning as an operation error.

```
(node:7203) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
We reproduced the issue with node v22.6.0
![image](https://github.com/user-attachments/assets/8cb230dd-80c4-47dd-abfd-a3143b39300a)



Please check your node version(node -v) and cli version(ares -V). We recommend to use node v16.20.2 and ares-cli v3.1.1 
After set node version to v16.20.2, please try to re-install ares-cli 
refer to : https://github.com/webos-tools/cli
 
```
npm uninstall -g @webos-tools/cli
npm install -g @webos-tools/cli
```
Thanks

**Comment by JamieNandhraPezone** [comment]
Downgrading node to 16.20.2 has worked! Thanks :)
